apiVersion: v1
kind: Secret
metadata:
  name: clustertree-cluster-manager
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  cert.pem: {{ .Values.clustertree.cert }}
  key.pem: {{ .Values.clustertree.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-plane-config
  namespace: {{ .Values.global.namespace }}
data:
  kubeconfig: {{ .Values.global.kubeconfig }}
