apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: {{ .Values.global.namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: {{ .Values.schedulerConfig.type }}
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: kosmos-scheduler
      resourceNamespace: {{ .Values.global.namespace }}    
    profiles:
      - schedulerName: {{ .Values.schedulerConfig.name }}
        plugins:
          preFilter:
            disabled:
              - name: "VolumeBinding"
            enabled:
              - name: "LeafNodeVolumeBinding"
          filter:
            disabled:
              - name: "VolumeBinding"
              - name: "TaintToleration"
            enabled:
              - name: "LeafNodeTaintToleration"
              - name: "LeafNodeVolumeBinding"
              - name: "LeafNodeDistribution"
          score:
            disabled:
              - name: "VolumeBinding"
          reserve:
            disabled:
              - name: "VolumeBinding"
            enabled:
              - name: "LeafNodeVolumeBinding"
          preBind:
            disabled:
              - name: "VolumeBinding"
            enabled:
              - name: "LeafNodeVolumeBinding"
        pluginConfig:
          - name: LeafNodeVolumeBinding
            args:
              bindTimeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: host-kubeconfig
  namespace: {{ .Values.global.namespace }}
data:
  kubeconfig: |
    apiVersion: {{ .Values.kubeconfig.apiVersion }}
    clusters:
    {{- if .Values.kubeconfig.clusters }}
      {{- with (index .Values.kubeconfig.clusters 0) }}
    - cluster:
        certificate-authority-data: {{ .cluster.authority | quote }}
        server: {{ .cluster.server | quote }}
      name: {{ .name | quote}}
      {{- end }}
    {{- else }}
    # No clusters found
    {{- end }}
    contexts:
    {{- if .Values.kubeconfig.contexts }}
      {{- with (index .Values.kubeconfig.contexts 0) }}
    - context:
        cluster: {{ .context.cluster | quote }}
        user: {{ .context.user | quote }}
      name: {{ .name | quote }}
      {{- end }}
    {{- else }}
    # No contexts found
    {{- end }}
    current-context: {{ .Values.kubeconfig.context | quote }}
    kind: {{ .Values.kubeconfig.kind | quote }}
    preferences: {{ .Values.kubeconfig.preferences | toYaml | nindent 4  }}
    users:
    {{- if .Values.kubeconfig.users }}
      {{- with (index .Values.kubeconfig.users 0) }}
    - name: {{ .name | quote }}
      user:
        client-certificate-data: {{ .user.certificate | quote }}
        client-key-data: {{ .user.key | quote }}
      {{- end }}
    {{- else }}
    # No users found
    {{- end }}
